#+TITLE: M2 Mycologie
#+SUBTITLE: Analyses RNA-Seq
#+DATE:
#+LANGUAGE: fr

* Principe des analyses RNA-Seq

- revues de bonnes pratiques : \cite{conesa-2016-survey-best,yendrek-2012-bench-scien}
- outils statistiques : [[https://www.bioconductor.org][Bioconductor]] ; \cite{korpelainen-2015-rna,anders-2013-count-rna}

* Etapes d'analyse

1. Extraction ADN à partir d'un échantillon
2. DNA sequencing
3. [*] Alignement des "reads" sur un génome de référence
4. Analyse exploratoire des données (contrôle qualité, couverture, etc.)
5. Identification des variants (SNP, indels -- small insertions and deletions)
6. Quantification de gènes (statistiques sur des données de comptage)

* Principes de l'analyse

Les "analyses NGS" (RNA, CHIP, etc.) doivent prendre en compte une estimation de la variance intra-groupe lors de l'analyse de multiples gènes, d'où l'idée de combiner l'information entre les gènes. L'approcge DESeq permet de détecter et corriger les estimations de dispersion qui restent trop faibles en modélisant la dépendance entre la dispersion de l'expression moyenne sur l'ensemble des échantillons. De plus, cette approche fournit une méthode originale de classement des gènes et de visualisation des tailles d'effet \cite{love-2014-moder-rna-deseq}. La librairie R [[https://bioconductor.org/packages/release/bioc/html/DESeq2.html][DESeq2]] fournit également des estimateurs de type "shrunken fold changes" (avec leur erreur-type).

* TopHat + HTSeq (or FeatureCounts)

Cette approche, disponible sous Galaxy, prend plus de temps et repose sur le logiciel TopHat. Celui-ci présente l'avantage de rendre compte des jonctions intron-exon, ce qui le distingue de bowtie.

* Kallisto (ultra-fast mapping)

- Entrée/Sortie = SRA ou Fastq et fichier d'annotation[fn::Attention : l'ID du transcrit doit correspondre exactement à l'ID du gène dans le fichier GFF3 d'annotation.] -> TPM
- plus rapide que TopHat, mais moins précis
- chaque "run" doit être en triplicat

#+BEGIN_EXAMPLE
target_id       length  eff_length      est_counts      tpm
jgi|Podans1|100005|CE99640_2373 1994    1895    1407    51.6298
jgi|Podans1|100060|CE99695_1372 3146    3047    504     11.502
jgi|Podans1|10015|CE9650_8706   1582    1483    1156    54.2042
#+END_EXAMPLE

* Fichier d'annotation (GFF3)

#+BEGIN_EXAMPLE
##gff-version 3
-%<-----
38763:scaffold_3 prediction gene 644807 646915 0 + . ID=gene_5098;Name=...
38764:scaffold_3 prediction mRNA 644807 646915 . + . ID=mRNA_5098;Name=...
#+END_EXAMPLE

* Analyse des données de comptage sous R

- nécessite deux data frames : un tableau avec les données de comptage (valeurs TPM obtenues avec =kallisto= ou =salmon=), et un tableau décrivant les conditions expérimentales.

#+BEGIN_SRC r
library("DESeq2")
library("tximport")
datadir <- dir(".", pattern = "out.\\.*")
files <- file.path(datadir, "abundance.h5")
names(files) <- gsub("out.", "", datadir)
samples <- data.frame(run = names(files), condition = c("4h", "48h", "24h"))
txi <- tximport(files, "kallisto", txOut = TRUE)
dds <- DESeqDataSetFromTximport(txi, colData = samples, design = ~ condition)
#+END_SRC

* Références
:PROPERTIES:
:BEAMER_opt: allowframebreaks,label=
:END:

#+LATEX: \printbibliography[heading=none]
