all:
	pandoc chapitre1.md chapitre2.md chapitre3.md  chapitre4.md chapitre5.md chapitre6.md chapitre7.md chapitre8.md chapitre9.md chapitre10.md chapitre11.md chapitre12.md annexes.md --pdf-engine=xelatex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V mainfont="Calibri" -o book.pdf
